[package]
name = "state-account"
version = "0.1.0"
authors = ["David Palm <dvdplm@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common-types = { path = "../types"}
ethcore-error = { path = "../ethcore-error" }
ethereum-types = "0.6.0"
ethtrie = { package = "patricia-trie-ethereum", path = "../../util/patricia-trie-ethereum" }
hash-db = "0.12.4"
keccak-hash = "0.2.0"
keccak-hasher = { path = "../../util/keccak-hasher" }
kvdb = "0.1.0"
log = "0.4"
lru-cache = "0.1.2"
parity-bytes = "0.1.0"
rlp = "0.4.0"
serde = { version = "1.0", features = ["derive"] }
trie-db = "0.12.4"
