[package]
name = "client-traits"
version = "0.1.0"
edition = "2018"


[dependencies]
call-contract = { package = "ethcore-call-contract", path = "../call-contract" }
common-types = { path = "../types" }
derive_more = "0.15.0"
ethereum-types = "0.6"
rlp = "0.4.0" # todo: only needed for `DecoderError` – fix
